/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    String n, p, namaInput, passInput;

    
    String getNama(){
        n = nama.getText();
        return n;
    }
    String getPassword(){
        p = password.getText();
        return p;
    }
    
    String getNamaInput(){
        return namaInput;
    }
    
    String getPassInput(){
        return passInput;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        masuk = new javax.swing.JToggleButton();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Pengumuman = new javax.swing.JLabel();
        panelutama = new javax.swing.JLabel();
        wadahnp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 193, 114));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 77, 71));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INI LOGIN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 50, 360, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        nama.setText("admin");
        nama.setMargin(new java.awt.Insets(5, 5, 5, 5));
        nama.setPreferredSize(new java.awt.Dimension(42, 30));
        jPanel2.add(nama);
        nama.setBounds(70, 50, 260, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 48, 63));
        jLabel4.setText("  Lupa Password ?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(220, 260, 110, 20);

        masuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        masuk.setText("L O G  I N");
        masuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masukMouseEntered(evt);
            }
        });
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        jPanel2.add(masuk);
        masuk.setBounds(20, 200, 310, 40);

        password.setText("admin");
        password.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel2.add(password);
        password.setBounds(70, 110, 260, 40);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-male-30.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 50, 40, 40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-lock-30.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 110, 40, 40);

        jCheckBox1.setForeground(new java.awt.Color(0, 48, 63));
        jCheckBox1.setText(" Remember Me ");
        jCheckBox1.setOpaque(false);
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(20, 260, 120, 20);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 320, 150, 100);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(270, 160, 360, 340);

        Pengumuman.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(Pengumuman);
        Pengumuman.setBounds(300, 510, 300, 90);

        panelutama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/8a4e1e8d6b340da246f22c5fac5b655e.jpg"))); // NOI18N
        jPanel1.add(panelutama);
        panelutama.setBounds(0, 0, 650, 660);

        wadahnp.setText("jLabel3");
        jPanel1.add(wadahnp);
        wadahnp.setBounds(380, 580, 180, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        masuk();
    }//GEN-LAST:event_masukActionPerformed

    public void masuk (){
 
        try {
            int no=1;
           Connect db = new Connect();
           String sql        = "SELECT Nama, Password FROM petugas WHERE Nama = '"+getNama()+"' AND Password = '"+getPassword()+"' ";

           Statement stat = (Statement) db.getConnection().createStatement();;
           ResultSet res= stat.executeQuery(sql);

            if (res.next())
            {   
                String dbasePassword=res.getString("Password").toString().trim();
                String enteredPassword=new String(password.getText().trim());
                String dbaseName=res.getString("Nama").toString().trim();
                String enteredName=new String(nama.getText().trim());
                
                namaInput = enteredName;
                passInput = enteredPassword;
                
                if(dbasePassword.equals(enteredPassword)){
                    if(dbaseName.equals(enteredName)){
                        Menu_Petugas_Utama obj=new Menu_Petugas_Utama();
                    obj.setVisible(true);
                    dispose();
                    }
                    
                }
                else{
                    Pengumuman.setText("Nama atau Password yang anda masukan salah");
                }
 	       
            }                     
            else
            {                  
                Pengumuman.setText("Nama atau Password yang anda masukan salah" + namaInput);             
            }                      
            stat.close();       
        }
        catch(SQLException se){
             se.printStackTrace();
        }
        catch(Exception e){
            e.printStackTrace();     
            Pengumuman.setText("Exception occurred while searching in the users table");
        }   
        
    }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Nama = admin, Password = admin");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void masukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masukMouseEntered
        // TODO add your handling code here:
        namaInput = nama.getText();
        passInput = password.getText();
        wadahnp.setText("test aja "+namaInput + passInput);
    }//GEN-LAST:event_masukMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pengumuman;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton masuk;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel panelutama;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel wadahnp;
    // End of variables declaration//GEN-END:variables
}
