
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author indiz
 */
public class Menu_Petugas_EditKatalog extends javax.swing.JFrame {

    
    
    private DefaultTableModel model;
    public int banyak;
    /**
     * Creates new form Menu
     */
    public Menu_Petugas_EditKatalog()  {
        initComponents();

          loadBuku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelJudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelNavBar = new javax.swing.JPanel();
        profileBtn = new javax.swing.JButton();
        katalogBtn = new javax.swing.JButton();
        pengembalianBtn = new javax.swing.JButton();
        peminjamanBtn = new javax.swing.JButton();
        laporanBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        panelAwal = new javax.swing.JPanel();
        Profile = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBuku = new javax.swing.JTable();
        Jumlah = new javax.swing.JLabel();
        IDBuku = new javax.swing.JLabel();
        JudulBuku = new javax.swing.JLabel();
        Penulis = new javax.swing.JLabel();
        Penerbit = new javax.swing.JLabel();
        Kategori = new javax.swing.JLabel();
        FJumlah = new javax.swing.JTextField();
        FIDBuku = new javax.swing.JTextField();
        FJudul = new javax.swing.JTextField();
        FPenulis = new javax.swing.JTextField();
        FPenerbit = new javax.swing.JTextField();
        FKategori = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        panelUtama.setBackground(new java.awt.Color(50, 50, 50));
        panelUtama.setMinimumSize(new java.awt.Dimension(720, 720));
        panelUtama.setPreferredSize(new java.awt.Dimension(720, 720));
        panelUtama.setLayout(null);

        panelJudul.setBackground(new java.awt.Color(33, 33, 33));
        panelJudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 50, 50)));
        panelJudul.setMinimumSize(new java.awt.Dimension(720, 90));
        panelJudul.setPreferredSize(new java.awt.Dimension(720, 90));
        panelJudul.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(33, 33, 33));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Utama Petugas");
        panelJudul.add(jLabel1);
        jLabel1.setBounds(27, 12, 250, 40);

        panelUtama.add(panelJudul);
        panelJudul.setBounds(0, 0, 720, 90);

        panelNavBar.setBackground(new java.awt.Color(33, 33, 33));
        panelNavBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 50, 50)));
        panelNavBar.setLayout(null);

        profileBtn.setBackground(new java.awt.Color(50, 50, 50));
        profileBtn.setForeground(new java.awt.Color(255, 243, 230));
        profileBtn.setText("Profile");
        profileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        panelNavBar.add(profileBtn);
        profileBtn.setBounds(0, 30, 150, 30);

        katalogBtn.setBackground(new java.awt.Color(50, 50, 50));
        katalogBtn.setForeground(new java.awt.Color(255, 243, 230));
        katalogBtn.setText("Katalog");
        katalogBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        katalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katalogBtnActionPerformed(evt);
            }
        });
        panelNavBar.add(katalogBtn);
        katalogBtn.setBounds(0, 60, 150, 30);

        pengembalianBtn.setBackground(new java.awt.Color(50, 50, 50));
        pengembalianBtn.setForeground(new java.awt.Color(255, 243, 230));
        pengembalianBtn.setText("Pengembalian");
        pengembalianBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pengembalianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianBtnActionPerformed(evt);
            }
        });
        panelNavBar.add(pengembalianBtn);
        pengembalianBtn.setBounds(0, 90, 150, 30);

        peminjamanBtn.setBackground(new java.awt.Color(50, 50, 50));
        peminjamanBtn.setForeground(new java.awt.Color(255, 243, 230));
        peminjamanBtn.setText("Peminjaman");
        peminjamanBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        peminjamanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanBtnActionPerformed(evt);
            }
        });
        panelNavBar.add(peminjamanBtn);
        peminjamanBtn.setBounds(0, 120, 150, 30);

        laporanBtn.setBackground(new java.awt.Color(50, 50, 50));
        laporanBtn.setForeground(new java.awt.Color(255, 243, 230));
        laporanBtn.setText("Laporan");
        laporanBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        laporanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanBtnActionPerformed(evt);
            }
        });
        panelNavBar.add(laporanBtn);
        laporanBtn.setBounds(0, 150, 150, 30);

        logoutBtn.setBackground(new java.awt.Color(50, 50, 50));
        logoutBtn.setForeground(new java.awt.Color(255, 243, 230));
        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        panelNavBar.add(logoutBtn);
        logoutBtn.setBounds(0, 490, 150, 25);

        panelUtama.add(panelNavBar);
        panelNavBar.setBounds(0, 90, 150, 550);

        panelAwal.setBackground(new java.awt.Color(33, 33, 33));
        panelAwal.setLayout(null);

        Profile.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Profile.setForeground(new java.awt.Color(255, 255, 255));
        Profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.setText("T A M B A H  K A T A L O G");
        panelAwal.add(Profile);
        Profile.setBounds(0, 0, 550, 70);

        TableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBuku);

        panelAwal.add(jScrollPane1);
        jScrollPane1.setBounds(40, 370, 500, 150);

        Jumlah.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Jumlah.setForeground(new java.awt.Color(255, 255, 255));
        Jumlah.setText("Jumlah");
        panelAwal.add(Jumlah);
        Jumlah.setBounds(50, 300, 75, 25);

        IDBuku.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        IDBuku.setForeground(new java.awt.Color(255, 255, 255));
        IDBuku.setText("ID Buku");
        panelAwal.add(IDBuku);
        IDBuku.setBounds(50, 100, 75, 25);

        JudulBuku.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JudulBuku.setForeground(new java.awt.Color(255, 255, 255));
        JudulBuku.setText("Judul");
        panelAwal.add(JudulBuku);
        JudulBuku.setBounds(50, 140, 75, 25);

        Penulis.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Penulis.setForeground(new java.awt.Color(255, 255, 255));
        Penulis.setText("Penulis");
        panelAwal.add(Penulis);
        Penulis.setBounds(50, 180, 75, 25);

        Penerbit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Penerbit.setForeground(new java.awt.Color(255, 255, 255));
        Penerbit.setText("Penerbit");
        panelAwal.add(Penerbit);
        Penerbit.setBounds(50, 220, 75, 25);

        Kategori.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Kategori.setForeground(new java.awt.Color(255, 255, 255));
        Kategori.setText("Kategori");
        panelAwal.add(Kategori);
        Kategori.setBounds(50, 260, 75, 25);

        FJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FJumlahActionPerformed(evt);
            }
        });
        panelAwal.add(FJumlah);
        FJumlah.setBounds(130, 300, 200, 25);

        FIDBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIDBukuActionPerformed(evt);
            }
        });
        panelAwal.add(FIDBuku);
        FIDBuku.setBounds(130, 100, 200, 25);

        FJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FJudulActionPerformed(evt);
            }
        });
        panelAwal.add(FJudul);
        FJudul.setBounds(130, 140, 200, 25);

        FPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPenulisActionPerformed(evt);
            }
        });
        panelAwal.add(FPenulis);
        FPenulis.setBounds(130, 180, 200, 25);

        FPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPenerbitActionPerformed(evt);
            }
        });
        panelAwal.add(FPenerbit);
        FPenerbit.setBounds(130, 220, 200, 25);

        FKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FKategoriActionPerformed(evt);
            }
        });
        panelAwal.add(FKategori);
        FKategori.setBounds(130, 260, 200, 25);

        Clear.setBackground(new java.awt.Color(49, 44, 81));
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });
        panelAwal.add(Clear);
        Clear.setBounds(440, 220, 100, 25);

        Tambah.setBackground(new java.awt.Color(49, 44, 81));
        Tambah.setForeground(new java.awt.Color(255, 255, 255));
        Tambah.setText("Tambah");
        Tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TambahMouseClicked(evt);
            }
        });
        panelAwal.add(Tambah);
        Tambah.setBounds(440, 100, 100, 25);

        Hapus.setBackground(new java.awt.Color(49, 44, 81));
        Hapus.setForeground(new java.awt.Color(255, 255, 255));
        Hapus.setText("Hapus");
        Hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HapusMouseClicked(evt);
            }
        });
        panelAwal.add(Hapus);
        Hapus.setBounds(440, 140, 100, 25);

        Update.setBackground(new java.awt.Color(49, 44, 81));
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        panelAwal.add(Update);
        Update.setBounds(440, 180, 100, 25);

        panelUtama.add(panelAwal);
        panelAwal.setBounds(150, 90, 570, 550);

        getContentPane().add(panelUtama);
        panelUtama.setBounds(0, 0, 730, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        Menu_Petugas_Profile MPP = new Menu_Petugas_Profile();
        MPP.setVisible(true);
        dispose();
    }//GEN-LAST:event_profileBtnActionPerformed

    private void laporanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanBtnActionPerformed
        // TODO add your handling code here:
        Menu_Petugas_Laporan MPL = new Menu_Petugas_Laporan();
        MPL.setVisible(true);
        dispose();
    }//GEN-LAST:event_laporanBtnActionPerformed

    private void katalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katalogBtnActionPerformed
        // TODO add your handling code here:
        Menu_Petugas_Katalog MPK = new Menu_Petugas_Katalog();
        MPK.setVisible(true);
        dispose();
    }//GEN-LAST:event_katalogBtnActionPerformed

    private void pengembalianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianBtnActionPerformed
        // TODO add your handling code here:
        Menu_Petugas_Pengembalian MPP = new Menu_Petugas_Pengembalian();
        MPP.setVisible(true);
        dispose();
    }//GEN-LAST:event_pengembalianBtnActionPerformed

    private void peminjamanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanBtnActionPerformed
        // TODO add your handling code here:
        Menu_Petugas_Peminjaman MPP = new Menu_Petugas_Peminjaman();
        MPP.setVisible(true);
        dispose();
    }//GEN-LAST:event_peminjamanBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Login L = new Login();
        L.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void FJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FJumlahActionPerformed

    private void FIDBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIDBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIDBukuActionPerformed

    private void FJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FJudulActionPerformed

    private void FPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FPenulisActionPerformed

    private void FPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FPenerbitActionPerformed

    private void FKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FKategoriActionPerformed

    private void TableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBukuMouseClicked
        // TODO add your handling code here:
        tampilrecord(evt);
        loadBuku();
        
    }//GEN-LAST:event_TableBukuMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        // TODO add your handling code here:
        kosong();
        loadBuku();
    }//GEN-LAST:event_ClearMouseClicked

    private void HapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusMouseClicked
        // TODO add your handling code here:
        hapus();
        loadBuku();
        kosong();
    }//GEN-LAST:event_HapusMouseClicked

    private void TambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahMouseClicked
        // TODO add your handling code here:
        tambah();
        loadBuku();
        kosong();
    }//GEN-LAST:event_TambahMouseClicked

    public void tampilrecord(java.awt.event.MouseEvent evt){
        //menampilkan record yg di click kedalam text field
        int baris = TableBuku.rowAtPoint(evt.getPoint());
        String a =TableBuku.getValueAt(baris, 0).toString();
        FIDBuku.setText(a);
        String b = TableBuku.getValueAt(baris,1).toString();
        FJudul.setText(b);       
        String c = TableBuku.getValueAt(baris, 2).toString();
        FPenulis.setText(c);
        String d = TableBuku.getValueAt(baris, 3).toString();
        FPenerbit.setText(d);
        String e = TableBuku.getValueAt(baris, 4).toString();
        FKategori.setText(e);
        String f = TableBuku.getValueAt(baris, 5).toString();
        FJumlah.setText(f);
    }

       private void kosong(){
    // menghapus data di textfield yg input
        FIDBuku.setText(null);
        FJudul.setText(null);
        FPenulis.setText(null);
        FPenerbit.setText(null);  
        FKategori.setText(null);
        FJumlah.setText(null);  
    } 
    
       public void hapus(){
           try {
               Connect c = new Connect();
            String sql ="delete from buku where ID_Buku='"+FIDBuku.getText()+"'";
            java.sql.Connection conn=(Connection) c.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Berhasil di Hapus");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       }
       
public void loadBuku(){
     //menghapus isi table tblGaji
        model =new DefaultTableModel();
        TableBuku.setModel(model);
        model.addColumn("ID Buku");
        model.addColumn("Nama Buku");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Kategori");
        model.addColumn("Jumlah");

     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Connect db = new Connect();
           Statement stat = (Statement) db.getConnection().createStatement();;
           String sql        = "Select * from buku";
           ResultSet res   = stat.executeQuery(sql);

           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[6];
                obj[0] = res.getString("ID_Buku"); 
                obj[1] = res.getString("Judul_Buku");
                obj[2] = res.getString("Penulis"); 
                obj[3] = res.getString("Penerbit");
                obj[4] = res.getString("Kategori");
                obj[5] = res.getString("Kuantiti");
         
                model.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
     banyak = model.getRowCount();
}
public void tambah(){
            try {
                Connect c = new Connect();
            String sql;
            sql = "INSERT INTO buku VALUES ('"+FIDBuku.getText()+"','"+FJudul.getText()+"','"+FPenulis.getText()+"','"+FPenerbit.getText()+"','"+FKategori.getText()+"','"+FJumlah.getText()+"')";
            java.sql.Connection conn=(Connection) c.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Petugas_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Petugas_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Petugas_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Petugas_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Petugas_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField FIDBuku;
    private javax.swing.JTextField FJudul;
    private javax.swing.JTextField FJumlah;
    private javax.swing.JTextField FKategori;
    private javax.swing.JTextField FPenerbit;
    private javax.swing.JTextField FPenulis;
    private javax.swing.JButton Hapus;
    private javax.swing.JLabel IDBuku;
    private javax.swing.JLabel JudulBuku;
    private javax.swing.JLabel Jumlah;
    private javax.swing.JLabel Kategori;
    private javax.swing.JLabel Penerbit;
    private javax.swing.JLabel Penulis;
    private javax.swing.JLabel Profile;
    private javax.swing.JTable TableBuku;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton katalogBtn;
    private javax.swing.JButton laporanBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel panelAwal;
    private javax.swing.JPanel panelJudul;
    private javax.swing.JPanel panelNavBar;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JButton peminjamanBtn;
    private javax.swing.JButton pengembalianBtn;
    private javax.swing.JButton profileBtn;
    // End of variables declaration//GEN-END:variables

    
}
