
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author indiz
 */
public class Menu_Petugas_Profile extends javax.swing.JFrame {

    
    private DefaultTableModel model;
    /**
     * Creates new form Menu
     */
    public Menu_Petugas_Profile()  {
        initComponents();
        //myinitComponents();
                model =new DefaultTableModel();
        Tabel.setModel(model);
        model.addColumn("NID");
        model.addColumn("Nama Guru");
        model.addColumn("Materi");
        model.addColumn("Lama Ajar");
          load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelJudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelNavBar = new javax.swing.JPanel();
        profileBtn = new javax.swing.JButton();
        katalogBtn = new javax.swing.JButton();
        pengembalianBtn = new javax.swing.JButton();
        peminjamanBtn = new javax.swing.JButton();
        laporanBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        panelAwal = new javax.swing.JPanel();
        Profile = new javax.swing.JLabel();
        NoTelepon = new javax.swing.JLabel();
        IdProfile = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        FieldIdProfile = new javax.swing.JTextField();
        FieldAlamat = new javax.swing.JTextField();
        FieldNama = new javax.swing.JTextField();
        FieldNoTelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 720));
        setSize(new java.awt.Dimension(720, 720));
        getContentPane().setLayout(null);

        panelUtama.setBackground(new java.awt.Color(50, 50, 50));
        panelUtama.setMinimumSize(new java.awt.Dimension(720, 720));
        panelUtama.setPreferredSize(new java.awt.Dimension(720, 720));
        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelUtamaMouseEntered(evt);
            }
        });
        panelUtama.setLayout(null);

        panelJudul.setBackground(new java.awt.Color(33, 33, 33));
        panelJudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 50, 50)));
        panelJudul.setMinimumSize(new java.awt.Dimension(720, 90));
        panelJudul.setPreferredSize(new java.awt.Dimension(720, 90));
        panelJudul.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(33, 33, 33));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Profile Petugas");
        panelJudul.add(jLabel1);
        jLabel1.setBounds(27, 12, 250, 40);

        panelUtama.add(panelJudul);
        panelJudul.setBounds(0, 0, 720, 90);

        panelNavBar.setBackground(new java.awt.Color(33, 33, 33));
        panelNavBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 50, 50)));
        panelNavBar.setLayout(null);

        profileBtn.setBackground(new java.awt.Color(50, 50, 50));
        profileBtn.setForeground(new java.awt.Color(255, 243, 230));
        profileBtn.setText("Profile");
        profileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        panelNavBar.add(profileBtn);
        profileBtn.setBounds(0, 30, 150, 30);

        katalogBtn.setBackground(new java.awt.Color(50, 50, 50));
        katalogBtn.setForeground(new java.awt.Color(255, 243, 230));
        katalogBtn.setText("Katalog");
        katalogBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelNavBar.add(katalogBtn);
        katalogBtn.setBounds(0, 60, 150, 30);

        pengembalianBtn.setBackground(new java.awt.Color(50, 50, 50));
        pengembalianBtn.setForeground(new java.awt.Color(255, 243, 230));
        pengembalianBtn.setText("Pengembalian");
        pengembalianBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelNavBar.add(pengembalianBtn);
        pengembalianBtn.setBounds(0, 90, 150, 30);

        peminjamanBtn.setBackground(new java.awt.Color(50, 50, 50));
        peminjamanBtn.setForeground(new java.awt.Color(255, 243, 230));
        peminjamanBtn.setText("Peminjaman");
        peminjamanBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelNavBar.add(peminjamanBtn);
        peminjamanBtn.setBounds(0, 120, 150, 30);

        laporanBtn.setBackground(new java.awt.Color(50, 50, 50));
        laporanBtn.setForeground(new java.awt.Color(255, 243, 230));
        laporanBtn.setText("Laporan");
        laporanBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        laporanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanBtnActionPerformed(evt);
            }
        });
        panelNavBar.add(laporanBtn);
        laporanBtn.setBounds(0, 150, 150, 30);

        logoutBtn.setBackground(new java.awt.Color(50, 50, 50));
        logoutBtn.setForeground(new java.awt.Color(255, 243, 230));
        logoutBtn.setText("Log Out");
        panelNavBar.add(logoutBtn);
        logoutBtn.setBounds(0, 490, 150, 25);

        panelUtama.add(panelNavBar);
        panelNavBar.setBounds(0, 90, 150, 550);

        panelAwal.setLayout(null);

        Profile.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.setText("P R O F I L E ");
        panelAwal.add(Profile);
        Profile.setBounds(0, 0, 550, 70);

        NoTelepon.setText("N O   T E L E P O N");
        panelAwal.add(NoTelepon);
        NoTelepon.setBounds(30, 290, 120, 40);

        IdProfile.setText("I D   P R O F I L E ");
        panelAwal.add(IdProfile);
        IdProfile.setBounds(30, 110, 100, 40);

        Nama.setText("NAMA");
        panelAwal.add(Nama);
        Nama.setBounds(30, 170, 100, 40);

        Alamat.setText("A L A M A T");
        panelAwal.add(Alamat);
        Alamat.setBounds(30, 230, 100, 40);

        FieldIdProfile.setEditable(false);
        panelAwal.add(FieldIdProfile);
        FieldIdProfile.setBounds(150, 110, 360, 40);

        FieldAlamat.setEditable(false);
        panelAwal.add(FieldAlamat);
        FieldAlamat.setBounds(150, 230, 360, 40);

        FieldNama.setEditable(false);
        panelAwal.add(FieldNama);
        FieldNama.setBounds(150, 170, 360, 40);

        FieldNoTelepon.setEditable(false);
        panelAwal.add(FieldNoTelepon);
        FieldNoTelepon.setBounds(150, 290, 360, 40);

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabel);

        panelAwal.add(jScrollPane1);
        jScrollPane1.setBounds(50, 370, 453, 130);

        panelUtama.add(panelAwal);
        panelAwal.setBounds(160, 100, 550, 540);

        getContentPane().add(panelUtama);
        panelUtama.setBounds(0, 0, 720, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        Menu_Petugas_Profile MPP;
        MPP = new Menu_Petugas_Profile();
        MPP.setVisible(true);
        dispose();
    }//GEN-LAST:event_profileBtnActionPerformed

    private void laporanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laporanBtnActionPerformed

    private void panelUtamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseEntered
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_panelUtamaMouseEntered

private void load(){
        // membuat tampilan model tabel
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
              Connect db = new Connect();
                 String sql        = "SELECT * FROM petugas";

           Statement stat = (Statement) db.getConnection();
           ResultSet res;
   //        ResultSet res   = stat.executeQuery(sql);
           
//        String sql        = "Select * from buku";
//        Statement stat = (Statement) Connect.getConnection().createStatement();
//        ResultSet res   = stat.executeQuery(sql);
            res = stat.executeQuery(sql);
 


            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            Tabel.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }



//     //menghapus isi table tblGaji
//     model.getDataVector( ).removeAllElements( );
//     model.fireTableDataChanged( );
//
//     try{
//           //membuat statemen pemanggilan data pada table tblGaji dari database
//           Statement stat = (Statement) Connect.getConnection().createStatement();
//           String sql        = "Select * from guru";
//           ResultSet res   = stat.executeQuery(sql);
//
//           //penelusuran baris pada tabel tblGaji dari database
//           while(res.next ()){
//                Object[ ] obj = new Object[6];
//                obj[0] = res.getString("ID_Guru"); 
//                obj[1] = res.getString("Nama_Guru");
//                obj[2] = res.getString("Materi"); 
//                obj[3] = res.getString("Jam_Ajar");
//         
//
//                model.addRow(obj);
//            }
//      }catch(SQLException err){
//            JOptionPane.showMessageDialog(null, err.getMessage() );
//      }  
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Petugas_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Petugas_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Petugas_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Petugas_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Petugas_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JTextField FieldAlamat;
    private javax.swing.JTextField FieldIdProfile;
    private javax.swing.JTextField FieldNama;
    private javax.swing.JTextField FieldNoTelepon;
    private javax.swing.JLabel IdProfile;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel NoTelepon;
    private javax.swing.JLabel Profile;
    private javax.swing.JTable Tabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton katalogBtn;
    private javax.swing.JButton laporanBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel panelAwal;
    private javax.swing.JPanel panelJudul;
    private javax.swing.JPanel panelNavBar;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JButton peminjamanBtn;
    private javax.swing.JButton pengembalianBtn;
    private javax.swing.JButton profileBtn;
    // End of variables declaration//GEN-END:variables

    
}
